"""add role to users and create student_profiles table

Revision ID: 45bd10fcb71f
Revises: d3d1ef52c7d2
Create Date: 2025-11-22 19:42:49.259998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45bd10fcb71f"
down_revision: Union[str, None] = "d3d1ef52c7d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_profiles",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_student_profiles_id"), "student_profiles", ["id"], unique=False
    )

    # Add role column as nullable first
    op.add_column("users", sa.Column("role", sa.String(), nullable=True))

    # Set default value for existing users
    op.execute("UPDATE users SET role = 'student' WHERE role IS NULL")

    # Now make the column non-nullable
    op.alter_column("users", "role", nullable=False, server_default="student")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.drop_index(op.f("ix_student_profiles_id"), table_name="student_profiles")
    op.drop_table("student_profiles")
    # ### end Alembic commands ###
