"""Add expires_at to test_attempts

Revision ID: 48f210f67d9b
Revises: 6ff9910ddc7d
Create Date: 2025-12-27 14:15:30.840644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f210f67d9b'
down_revision: Union[str, None] = '6ff9910ddc7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_attempts', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_attempts', 'expires_at')
    # ### end Alembic commands ###
