"""Make payment_id nullable in student_test_registration

Revision ID: 6ff9910ddc7d
Revises: 273c1c8cad84
Create Date: 2025-12-04 19:04:47.737800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff9910ddc7d'
down_revision: Union[str, None] = '273c1c8cad84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_test_registration', 'payment_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_test_registration', 'payment_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
